require 'onesky/rails/client'
require 'yaml'

module Onesky
  module Rails

    class FileClient < Onesky::Rails::Client

      FILE_FORMAT = 'RUBY_YAML'
      ENCODING    = 'UTF-8'
      DIR_PREFIX  = 'onesky_'
      TRANSLATION_NOTICE = <<-NOTICE
# This file is generated by onesky-rails gem and will be overwritten at the next download
# Therefore, you should not modify this file
# If you want to modify the translation, please do it at OneSky platform
# If you still want to modify this file directly, please upload this file to OneSky platform after modification in order to update the translation at OneSky

NOTICE

      def upload(string_path)
        verify_languages!

        get_default_locale_files(string_path).map do |path|
          filename = File.basename(path)
          puts "Uploading #{filename}"
          @project.upload_file(file: path, file_format: FILE_FORMAT, is_keeping_all_strings: is_keep_strings?)
          path
        end
      end

      def download(string_path)
        verify_languages!

        files = get_default_locale_files(string_path).map {|path| File.basename(path)}

        @onesky_locales.each do |locale|
          puts "#{locale_dir(locale)}/"
          onesky_locale = locale.gsub('_', '-')
          files.each do |file|
            response = @project.export_translation(source_file_name: file, locale: onesky_locale)
            if response.code == 200
              saved_file = save_translation(response, string_path, locale, file)
              puts "  #{saved_file}"
            end
          end
        end
      end

      protected

      def locale_dir(locale)
        DIR_PREFIX + locale
      end

      def make_translation_dir(dir_path, locale)
        target_path = File.join(dir_path, locale_dir(locale))
        Dir.mkdir(target_path) unless File.directory?(target_path)
        target_path
      end

      def locale_file_name(file, to_locale)
        file.sub(@base_locale.to_s, to_locale)
      end

      def get_default_locale_files(string_path)
        Dir.glob("#{string_path}/**/*.yml").map do |path|
          content_hash = YAML.load_file(path)
          path if content_hash && content_hash.has_key?(@base_locale.to_s)
        end.compact
      end

      def save_translation(response, string_path, locale, file)
        locale_path = make_translation_dir(string_path, locale)
        target_file = locale_file_name(file, locale)

        File.open(File.join(locale_path, target_file), 'w') do |f|
          f.write(TRANSLATION_NOTICE + response.body.force_encoding(ENCODING))
        end
        target_file
      end

      def is_keep_strings?
        return true unless (@config.has_key?('upload') && @config['upload'].has_key?('is_keeping_all_strings'))

        !!@config['upload']['is_keeping_all_strings']
      end

    end

  end
end
